### ISSUE TITLE
[Unsure] support for OpenAPI v. 3.0.0

### ISSUE THREAD

**Issue by greatvovan** [lucybot/lucy-console#89]
I have an OpenAPI specification v. 3.0.0 in YAML format. I converted it to JSON and put into the root directory as suggested, but the rendering I see is very poor, it only contains the top-level list of methods and that's all. If I click on a method, it shows method's description, list of parameters and response code tabs, but everything with empty content.

![image](https://user-images.githubusercontent.com/4903007/96945928-de76ae80-1493-11eb-8a25-535dbafb672b.png)

I am wondering if it is something related to my JSON file and how it can be fixed. Does the tool support `"openapi": "3.0.0"` at all?

**Comment by greatvovan** [comment]
I was able to make it work by converting to Swagger 2.0 using https://github.com/LucyBot-Inc/api-spec-converter, so I think my guess was correct. However taking into account the fact that OpenAPI 3.0.0 is the standard now, the native support would be appreciated. As an option, the tool can use this converter internally and transparently for users.

**Comment by rbren** [comment]
Yes, unfortunately we don't have any plans for 3.0 support, aside from down-converting to 2.0
